# Generated by Django 3.2.12 on 2022-03-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply_for',
            fields=[
                ('applyforId', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='申购编号')),
                ('material_id', models.CharField(default=0, max_length=200, verbose_name='物料编号')),
                ('material_name', models.CharField(max_length=100, verbose_name='物料名称')),
                ('material_Model_number', models.CharField(max_length=100, verbose_name='物料型号')),
                ('material_describe', models.TextField(blank=True, verbose_name='物料描述')),
                ('material_use', models.TextField(blank=True, verbose_name='物料用途')),
                ('material_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='物料单价')),
                ('purchase_amount', models.IntegerField(verbose_name='采购数量')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=13, verbose_name='采购金额')),
                ('purchase_people', models.CharField(default='', max_length=200, verbose_name='采购人员')),
                ('is_apply', models.BooleanField(default=False, verbose_name='是否提交')),
            ],
            options={
                'verbose_name': '申购表',
                'verbose_name_plural': '申购表',
                'db_table': 'apply_for',
            },
        ),
        migrations.CreateModel(
            name='ApplyOutLib',
            fields=[
                ('apply_number', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='申请编号')),
                ('receive_number', models.CharField(max_length=200, verbose_name='领料编号')),
                ('inventory_number', models.CharField(default='', max_length=200, verbose_name='库存编号')),
                ('apply_time', models.DateTimeField(default='2022-03-11 14:17:14', verbose_name='申请时间')),
                ('material_id', models.CharField(default=0, max_length=200, verbose_name='物料编号')),
                ('material_name', models.CharField(max_length=100, verbose_name='物料名称')),
                ('material_Model_number', models.CharField(max_length=100, verbose_name='物料型号')),
                ('material_describe', models.TextField(blank=True, verbose_name='物料描述')),
                ('material_use', models.TextField(blank=True, verbose_name='用途描述')),
                ('out_of_amount', models.IntegerField(default=0, verbose_name='申请数量')),
                ('apply_people', models.CharField(default='', max_length=200, verbose_name='申请人员')),
                ('is_agree', models.BooleanField(default=False, verbose_name='是否同意')),
            ],
            options={
                'verbose_name': '领料申请表',
                'verbose_name_plural': '领料申请表',
                'db_table': 'ApplyOutLib',
            },
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('inventory_number', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='库存编号')),
                ('material_id', models.CharField(default=0, max_length=200, verbose_name='物料编号')),
                ('material_name', models.CharField(max_length=100, verbose_name='物料名称')),
                ('material_Model_number', models.CharField(max_length=100, verbose_name='物料型号')),
                ('material_describe', models.TextField(blank=True, verbose_name='物料描述')),
                ('material_use', models.TextField(blank=True, verbose_name='用途描述')),
                ('position', models.CharField(default='', max_length=200, verbose_name='库存位置')),
                ('put_in_amount', models.IntegerField(default=0, verbose_name='入库数量')),
                ('out_of_amount', models.IntegerField(default=0, verbose_name='出库数量')),
                ('surplus_amount', models.IntegerField(default=0, verbose_name='剩余库存')),
            ],
            options={
                'verbose_name': '库存表',
                'verbose_name_plural': '库存表',
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='物料编号')),
                ('material_name', models.CharField(max_length=100, verbose_name='物料名称')),
                ('material_Model_number', models.CharField(max_length=100, verbose_name='物料型号')),
                ('material_describe', models.TextField(blank=True, verbose_name='物料描述')),
                ('material_use', models.TextField(blank=True, verbose_name='物料用途')),
                ('disburse_company', models.CharField(max_length=100, verbose_name='支出公司')),
            ],
            options={
                'verbose_name': '物料表',
                'verbose_name_plural': '物料表',
                'db_table': 'material',
            },
        ),
        migrations.CreateModel(
            name='out_of_library',
            fields=[
                ('out_of_number', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='出库编号')),
                ('receive_number', models.CharField(default='', max_length=200, verbose_name='领料编号')),
                ('inventory_number', models.CharField(default='', max_length=200, verbose_name='库存编号')),
                ('out_of_time', models.DateTimeField(default='2022-03-11 14:17:14', verbose_name='出库时间')),
                ('material_id', models.CharField(default=0, max_length=200, verbose_name='物料编号')),
                ('material_name', models.CharField(max_length=100, verbose_name='物料名称')),
                ('material_Model_number', models.CharField(max_length=100, verbose_name='物料型号')),
                ('material_describe', models.TextField(blank=True, verbose_name='物料描述')),
                ('material_use', models.TextField(blank=True, verbose_name='用途描述')),
                ('out_of_amount', models.IntegerField(default=0, verbose_name='出库数量')),
                ('material_handler', models.CharField(default='', max_length=200, verbose_name='领料人员')),
            ],
            options={
                'verbose_name': '出库记录表',
                'verbose_name_plural': '出库记录表',
                'db_table': 'outOfLibrary',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_number', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='采购单号')),
                ('purchase_time', models.DateTimeField(default='2022-03-11 14:17:14', verbose_name='采购时间')),
                ('material_id', models.CharField(default=0, max_length=200, verbose_name='物料编号')),
                ('material_name', models.CharField(max_length=100, verbose_name='物料名称')),
                ('material_Model_number', models.CharField(max_length=100, verbose_name='物料型号')),
                ('material_describe', models.TextField(blank=True, verbose_name='物料描述')),
                ('material_use', models.TextField(blank=True, verbose_name='用途描述')),
                ('material_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=13, verbose_name='成交单价')),
                ('purchase_amount', models.IntegerField(verbose_name='采购数量')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=13, verbose_name='采购金额')),
                ('purchase_people', models.CharField(default='', max_length=200, verbose_name='采购人')),
                ('disburse_company', models.CharField(max_length=100, verbose_name='支出公司')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否已审核')),
                ('is_putintolib', models.BooleanField(default=False, verbose_name='是否入库')),
            ],
            options={
                'verbose_name': '采购表',
                'verbose_name_plural': '采购表',
                'db_table': 'purchase',
            },
        ),
        migrations.CreateModel(
            name='putintoStorage',
            fields=[
                ('PISnumber', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='入库编号')),
                ('PIStime', models.DateTimeField(default='2022-03-11 14:17:14', verbose_name='入库时间')),
                ('material_id', models.CharField(default=0, max_length=200, verbose_name='物料编号')),
                ('material_name', models.CharField(max_length=100, verbose_name='物料名称')),
                ('material_Model_number', models.CharField(max_length=100, verbose_name='物料型号')),
                ('material_describe', models.TextField(blank=True, verbose_name='物料描述')),
                ('material_use', models.TextField(blank=True, verbose_name='用途描述')),
                ('amount', models.IntegerField(default=0, verbose_name='入库数量')),
                ('PutPeople', models.CharField(default='', max_length=200, verbose_name='送料人员')),
                ('is_putintosttorage', models.BooleanField(default=False, verbose_name='是否更新库存')),
            ],
            options={
                'verbose_name': '入库记录表',
                'verbose_name_plural': '入库记录表',
                'db_table': 'putIntoStorage',
            },
        ),
        migrations.CreateModel(
            name='receive',
            fields=[
                ('receive_number', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='领料编号')),
                ('inventory_number', models.CharField(default='', max_length=200, verbose_name='库存编号')),
                ('material_id', models.CharField(default=0, max_length=200, verbose_name='物料编号')),
                ('material_name', models.CharField(max_length=100, verbose_name='物料名称')),
                ('material_Model_number', models.CharField(max_length=100, verbose_name='物料型号')),
                ('material_describe', models.TextField(blank=True, verbose_name='物料描述')),
                ('material_use', models.TextField(blank=True, verbose_name='用途描述')),
                ('position', models.CharField(default='', max_length=200, verbose_name='库存位置')),
                ('receive_amount', models.IntegerField(default=0, verbose_name='领取数量')),
                ('receive_people', models.CharField(default='', max_length=200, verbose_name='领料人')),
                ('is_submit', models.BooleanField(default=False, verbose_name='是否提交')),
            ],
            options={
                'verbose_name': '领料表',
                'verbose_name_plural': '领料表',
                'db_table': 'receive',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('Userrank', models.BooleanField(default=False, verbose_name='用户等级')),
            ],
            options={
                'verbose_name': '用户信息表',
                'verbose_name_plural': '用户信息表',
                'db_table': 'userinfo',
            },
        ),
    ]
